### ISSUE TITLE
Pimatic stops without network

### ISSUE THREAD

**Issue by vdancsi** [mwittig/pimatic-unipi-evok#20]
Hi!

I have a strange issue. I have a Unipi Neuron device installed EVOK2.0 and Pimatic on it. Raspberry is set to fix IP, plugin installed on Pimatic. I connect to it directly with a windows computer, everything works fine, until I disconnect the computer. EVOK keeps working (inputs trigger outputs), but Pimatic rules stop working. I think it is some network related setting, but could not figure it out so far... Thank you for the help in advance...

**Comment by mwittig** [comment]
Sorry for the delay in reply. Currently, I have no clue what the problem is about. 

- Does the problem still exist? 
- Which Evok version did you install (the latest is 2.0.7a)?
- Do you have an example for a rule which apparebtly does no longer work?
- Do you see one or more error messages/warnings in the  pimatic log file when the computer is disconnected?
- Do the rules work again when you restart pimatic without connecting to it from the Windows computer (you can restart pimatic from the linux command line)?

**Comment by mwittig** [comment]
Assume this has been resolved. Re-open otherwise
